Repository bpmn-io/form-js, pull requests merged in 2023-07, with the labels that each got.

#697 Fix Carbonization
  packages/form-js-carbon-styles/src/carbon-styles.js
  packages/form-js-carbon-styles/test/spec/carbon-styles.spec.js
  packages/form-js-viewer/assets/form-js-base.css
Labels: needs review

#700 chore(CHANGELOG): update to v1.0.0
  packages/form-js/CHANGELOG.md
Labels: needs review, deploy-preview

#704 ci: update ADD_TO_HTO_PROJECT action
  .github/workflows/ADD_TO_HTO_PROJECT.yml
Labels: enhancement, needs review

#714 test: Fix visual regression integration linking
  .github/workflows/TASKLIST_CARBONISATION.yml
Labels: needs review

#715 chore: Update Playwright
  .github/workflows/VISUAL_REGRESSION.yml
  package-lock.json
  package.json
Labels: needs review

#720 fix: hide empty rows via css
  packages/form-js-viewer/assets/form-js-base.css
Labels: needs review

#728 fix: serialize empty text as empty string
  packages/form-js-editor/src/features/properties-panel/entries/TextEntry.js
Labels: needs review, deploy-preview

#736 fix: break overflowing words in text views
  packages/form-js-viewer/assets/form-js-base.css
Labels: needs review, deploy-preview

#737 fix: textarea resizing behavior improvements
  packages/form-js-viewer/src/render/components/form-fields/Textarea.js
Labels: needs review, deploy-preview

#734 fix: render text placeholder for whitespace values
  packages/form-js-editor/src/render/components/editor-form-fields/EditorText.js
  packages/form-js-editor/test/spec/render/components/form-fields/EditorText.spec.js
Labels: needs review, deploy-preview

#744 chore(GHA): overwrite screenshots on master/dev
  .github/workflows/VISUAL_REGRESSION.yml
Labels: needs review

#725 feat: empty form editor state
  packages/form-js-editor/assets/form-js-editor-base.css
  packages/form-js-editor/src/render/components/FormEditor.js
  packages/form-js-editor/src/render/components/icons/EmptyForm.svg
  packages/form-js-editor/src/render/components/icons/index.js
  packages/form-js-editor/test/spec/FormEditor.spec.js
Labels: in progress, deploy-preview

#748 feat: improve spacer visuals
  packages/form-js-editor/assets/form-js-editor-base.css
  packages/form-js-editor/src/render/components/editor-form-fields/EditorSpacer.js
  packages/form-js-editor/src/render/components/editor-form-fields/index.js
Labels: needs review, deploy-preview

#610 feat: implement validate on blur & input
  package-lock.json
  packages/form-js-viewer/src/Form.js
  packages/form-js-viewer/src/features/index.js
  packages/form-js-viewer/src/features/viewerCommands/ViewerCommands.js
  packages/form-js-viewer/src/features/viewerCommands/cmd/UpdateFieldValidationHandler.js
  packages/form-js-viewer/src/features/viewerCommands/index.js
  packages/form-js-viewer/src/render/components/FormField.js
  packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
  packages/form-js-viewer/src/render/components/form-fields/Checklist.js
  packages/form-js-viewer/src/render/components/form-fields/Datetime.js
  packages/form-js-viewer/src/render/components/form-fields/Number.js
  packages/form-js-viewer/src/render/components/form-fields/Radio.js
  packages/form-js-viewer/src/render/components/form-fields/Select.js
  packages/form-js-viewer/src/render/components/form-fields/Taglist.js
  packages/form-js-viewer/src/render/components/form-fields/Textarea.js
  packages/form-js-viewer/src/render/components/form-fields/Textfield.js
  packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
  packages/form-js-viewer/src/render/components/form-fields/parts/SearchableSelect.js
  packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js
  packages/form-js-viewer/src/render/components/form-fields/parts/Timepicker.js
  packages/form-js-viewer/test/spec/Form.spec.js
  packages/form-js-viewer/test/spec/render/components/FormField.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Checkbox.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Checklist.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Radio.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Textarea.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/helper/index.js
Labels: needs review, deploy-preview

#751 feat(props): implement first set of tooltips
  package-lock.json
  packages/form-js-editor/package.json
  packages/form-js-editor/src/features/properties-panel/PropertiesPanel.js
  packages/form-js-editor/src/features/properties-panel/entries/AltTextEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/DisabledEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/ImageSourceEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/KeyEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/ReadonlyEntry.js
  packages/form-js-editor/src/features/properties-panel/groups/CustomPropertiesGroup.js
  packages/form-js-editor/src/features/properties-panel/groups/ValuesGroups.js
  packages/form-js-editor/src/features/properties-panel/groups/index.js
  packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
Labels: needs review, deploy-preview
