Repository bpmn-io/form-js, pull requests merged in 2023-01, with the labels that each got.

#476 feat: simplify checklist icon
  packages/form-js-viewer/src/render/components/icons/Checklist.svg
Labels: needs review

#484 fix: clear custom validation when using presets
  packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
  packages/form-js-editor/test/spec/features/properties-panel/groups/ValidationGroup.spec.js
Labels: needs review

#482 feat: Make datetime picker SVG color customisable
  packages/form-js-viewer/assets/form-js.css
  packages/form-js-viewer/src/render/components/form-fields/icons/Calendar.svg
  packages/form-js-viewer/src/render/components/form-fields/icons/Clock.svg
Labels: needs review

#488 fix(playground): props panel no longer squashes
  packages/form-js-playground/src/components/PlaygroundRoot.css
Labels: in progress

#493 fix: do not serialize standalone minus in numberField
  packages/form-js-viewer/src/render/components/form-fields/Number.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
Labels: needs review

#494 fix: use proper variable for increment validation
  packages/form-js-viewer/src/core/Validator.js
  packages/form-js-viewer/test/spec/core/Validator.spec.js
Labels: needs review

#498 fix: decimal values for min/max number validation
  packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
  packages/form-js-editor/test/spec/features/properties-panel/groups/ValidationGroup.spec.js
Labels: needs review

#495 fix: display datetime time value when disabled
  packages/form-js-viewer/src/render/components/form-fields/Datetime.js
  packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js
Labels: needs review

#490 fix: trim increment number value
  packages/form-js-editor/src/features/properties-panel/entries/NumberEntries.js
  packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
Labels: needs review

#500 fix: Remove important from flatpicker CSS override
  packages/form-js-viewer/assets/form-js.css
Labels: needs review

#501 fix: don't collapse dropdownlist on click scroll
  packages/form-js-viewer/src/render/components/form-fields/parts/DropdownList.js
Labels: needs review

#502 chore(CHANGELOG): update to v0.11.0
  packages/form-js/CHANGELOG.md
Labels: needs review

#485 fix(editor): remove custom validate via behavior
  packages/form-js-editor/src/features/modeling/behavior/ValidateBehavior.js
  packages/form-js-editor/src/features/modeling/behavior/index.js
  packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
  packages/form-js-editor/test/spec/features/modeling/behavior/ValidateBehavior.spec.js
  packages/form-js-editor/test/spec/features/properties-panel/groups/ValidationGroup.spec.js
Labels: needs review

#514 fix: provide default values on static source
  packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
  packages/form-js-viewer/src/util/constants/ValuesSourceConstants.js
Labels: needs review

#511 docs: update FORM_SCHEMA.md
  docs/FORM_SCHEMA.md
Labels: needs review

#516 chore: properties panel renames
  packages/form-js-editor/src/features/properties-panel/entries/NumberSerializationEntry.js
  packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
  packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
Labels: needs review

#513 feat(editor): emit `drag` events
  packages/form-js-editor/src/render/components/FormEditor.js
  packages/form-js-editor/test/spec/FormEditor.spec.js
Labels: needs review

#518 feat(editor): disable text links
  packages/form-js-viewer/assets/form-js.css
  packages/form-js-viewer/src/render/components/form-fields/Text.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js
Labels: needs review

#512 fix: display `taglist` disabled state properly
  packages/form-js-viewer/assets/form-js.css
  packages/form-js-viewer/src/render/components/form-fields/Number.js
  packages/form-js-viewer/src/render/components/form-fields/Taglist.js
  packages/form-js-viewer/src/render/components/form-fields/parts/InputAdorner.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
Labels: needs review

#520 fix: disable user-select on drag containers
  packages/form-js-editor/assets/form-js-editor.css
Labels: needs review, spring cleaning

#525 feat: normalized font and misc styling form-wide
  packages/form-js-editor/assets/form-js-editor.css
  packages/form-js-viewer/assets/form-js.css
  packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js
Labels: needs review
