Repository bpmn-io/form-js, pull requests merged in 2023-03, with the labels that each got.

#563 fix(editor): use proper empty value for select defaults
  packages/form-js-editor/src/features/properties-panel/entries/DefaultValueEntry.js
  packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
  packages/form-js/CHANGELOG.md
Labels: needs review, deploy-preview

#570 Fixed transparent input backgrounds and disabled state borders
  packages/form-js-viewer/assets/form-js-base.css
Labels: in progress, deploy-preview

#578 chore: update to `schemaVersion@8`
  docs/FORM_SCHEMA.md
  packages/form-js-viewer/src/index.js
  packages/form-js/test/spec/Form.spec.js
Labels: needs review

#574 chore(CHANGELOG): update to v0.13.0
  packages/form-js/CHANGELOG.md
Labels: needs review

#579 ci(POST_RELEASE): use Node@16
  .github/workflows/POST_RELEASE.yml
Labels: needs review
