Repository bpmn-io/form-js, pull requests merged in 2023-04, with the labels that each got.

#590 fix: made editor buttons clickthrough
  packages/form-js-editor/assets/form-js-editor-base.css
Labels: needs review

#595 feat: implemented `required` where it was missing
  packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
  packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
  packages/form-js-editor/test/spec/features/properties-panel/groups/ValidationGroup.spec.js
  packages/form-js-viewer/assets/form-js-base.css
  packages/form-js-viewer/src/core/Validator.js
  packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
  packages/form-js-viewer/src/render/components/form-fields/Checklist.js
  packages/form-js-viewer/src/render/components/form-fields/Taglist.js
  packages/form-js-viewer/test/spec/core/Validator.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Checkbox.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Checklist.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Radio.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Textarea.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js
Labels: needs review, deploy-preview

#600 style: properly align rows in viewer
  packages/form-js-playground/src/components/PlaygroundRoot.css
  packages/form-js-viewer/assets/form-js-base.css
Labels: needs review

#597 fix: compare labels properly in unique validation
  packages/form-js-editor/src/features/properties-panel/entries/StaticValuesSourceEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/ValueEntry.js
  packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
Labels: in progress

#603 fix: getSchemaVariable accounts for feelers expressions
  packages/form-js-viewer/src/features/expression-language/FeelExpressionLanguage.js
  packages/form-js-viewer/src/features/expression-language/FeelersTemplating.js
  packages/form-js-viewer/src/features/expression-language/variableExtractionHelpers.js
  packages/form-js-viewer/src/util/index.js
  packages/form-js-viewer/test/spec/features/expression-language/FeelExpressionLanguage.spec.js
  packages/form-js-viewer/test/spec/template-variable-complex.json
  packages/form-js-viewer/test/spec/template-variable.json
  packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js
Labels: needs review

#613 feat: added textLinkTarget property to form-viewer
  packages/form-js-playground/src/components/PlaygroundRoot.js
  packages/form-js-viewer/src/render/components/form-fields/Text.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js
Labels: needs review

#615 fix: custom properties/static values redundancy
  packages/form-js-editor/src/features/properties-panel/entries/StaticValuesSourceEntry.js
  packages/form-js-editor/src/features/properties-panel/groups/CustomValuesGroup.js
  packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
  packages/form-js-editor/test/spec/redundantValues.json
Labels: needs review

#619 feat(playground): set aria-label for each component
  packages/form-js-editor/src/render/components/FormEditor.js
  packages/form-js-playground/src/components/JSONEditor.js
  packages/form-js-playground/src/components/PlaygroundRoot.js
  packages/form-js-playground/test/spec/Playground.spec.js
  packages/form-js-viewer/src/render/components/FormComponent.js
Labels: needs review, spring cleaning

#618 fix: prioritize adorner sizing
  packages/form-js-viewer/assets/form-js-base.css
Labels: in progress, deploy-preview

#626 feat: Correlate error messages to fields
  packages/form-js-viewer/src/render/components/Errors.js
  packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
  packages/form-js-viewer/src/render/components/form-fields/Checklist.js
  packages/form-js-viewer/src/render/components/form-fields/Datetime.js
  packages/form-js-viewer/src/render/components/form-fields/Number.js
  packages/form-js-viewer/src/render/components/form-fields/Radio.js
  packages/form-js-viewer/src/render/components/form-fields/Select.js
  packages/form-js-viewer/src/render/components/form-fields/Taglist.js
  packages/form-js-viewer/src/render/components/form-fields/Textarea.js
  packages/form-js-viewer/src/render/components/form-fields/Textfield.js
  packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
  packages/form-js-viewer/src/render/components/form-fields/parts/SearchableSelect.js
  packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js
  packages/form-js-viewer/src/render/components/form-fields/parts/Timepicker.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Checkbox.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Checklist.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Radio.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Textarea.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js
Labels: needs review

#627 style(editor): set width to drop containers
  packages/form-js-editor/assets/form-js-editor-base.css
Labels: needs review, deploy-preview

#625 fix: sanitize textfield newlines
  packages/form-js-viewer/src/render/components/form-fields/Textfield.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js
Labels: needs review

#630 fix: adjusted component lib search
  packages/form-js-editor/src/features/palette/components/Palette.js
  packages/form-js-editor/test/spec/features/palette/Palette.spec.js
Labels: needs review, deploy-preview

#629 fix: more gracefully handle tiny fields with adorners
  packages/form-js-viewer/assets/form-js-base.css
Labels: needs review

#631 fix: support markdown tables
  packages/form-js-viewer/src/render/components/Sanitizer.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js
Labels: needs review, deploy-preview

#632 test: Setup visual regression tests
  .github/workflows/VISUAL_REGRESSION.yml
  .gitignore
  README.md
  e2e/README.md
  e2e/index.html
  e2e/main.js
  e2e/visual/empty-ui.spec.js
  e2e/visual/empty-ui.spec.js-snapshots/empty-playground-1-chromium-linux.png
  e2e/visual/empty-ui.spec.js-snapshots/empty-playground-1-firefox-linux.png
  e2e/visual/empty-ui.spec.js-snapshots/empty-playground-1-webkit-linux.png
  package-lock.json
  package.json
  playwright.config.js
  vite.config.js
Labels: needs review
