Repository bpmn-io/form-js, pull requests merged in 2024-01, with the labels that each got.

#959 feat: Implement form-js viewer debounce
  packages/form-js-editor/src/FormEditor.js
  packages/form-js-viewer/src/Form.js
  packages/form-js-viewer/src/index.js
  packages/form-js-viewer/src/render/components/form-fields/Number.js
  packages/form-js-viewer/src/render/components/form-fields/Textarea.js
  packages/form-js-viewer/src/render/components/form-fields/Textfield.js
  packages/form-js-viewer/src/render/hooks/useFlushDebounce.js
  packages/form-js-viewer/test/spec/Form.spec.js
  packages/form-js-viewer/test/spec/render/components/helper/mocks/index.js
Labels: needs review

#963 fix: properly handle all formats of options sources
  package-lock.json
  packages/form-js-viewer/package.json
  packages/form-js-viewer/src/render/components/form-fields/Checklist.js
  packages/form-js-viewer/src/render/components/form-fields/Radio.js
  packages/form-js-viewer/src/render/components/form-fields/Taglist.js
  packages/form-js-viewer/src/render/components/form-fields/parts/SearchableSelect.js
  packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js
  packages/form-js-viewer/src/render/components/util/optionsUtil.js
  packages/form-js-viewer/src/render/components/util/sanitizerUtil.js
  packages/form-js-viewer/src/render/hooks/useCleanupMultiSelectValues.js
  packages/form-js-viewer/src/render/hooks/useCleanupSingleSelectValue.js
  packages/form-js-viewer/src/render/hooks/useGetLabelCorrelation.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Checklist.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Radio.spec.js
  packages/form-js-viewer/test/spec/render/components/form-fields/util/optionsUtil.spec.js
Labels: needs review, deploy-preview

#969 fix: revert debounce functionality on number fields
  packages/form-js-viewer/src/render/components/form-fields/Number.js
Labels: needs review, deploy-preview

#971 fix: explicitly depend on lodash
  package-lock.json
  packages/form-js-viewer/package.json
Labels: needs review

#978 Use named exports in playground
  packages/form-js-playground/src/Playground.js
  packages/form-js-playground/src/components/JSONEditor.js
  packages/form-js-playground/src/components/autocompletion/index.js
  packages/form-js-playground/src/index.js
  packages/form-js-playground/test/custom/editor.js
  packages/form-js-playground/test/custom/viewer.js
  packages/form-js-playground/test/spec/Playground.spec.js
Labels: needs review

#980 fix: explicitely align table entries to center
  packages/form-js-viewer/assets/form-js-base.css
Labels: needs review

#982 fix: improve text prompts of empty group components
  packages/form-js-editor/assets/form-js-editor-base.css
  packages/form-js-editor/src/render/components/FormEditor.js
Labels: needs review, deploy-preview

#986 fix(markdown): add margins to all markdown elements
  e2e/visual/carbon-styles.spec.js-snapshots/carbon-styles-1-chromium-linux.png
  e2e/visual/carbon-styles.spec.js-snapshots/carbon-styles-1-firefox-linux.png
  e2e/visual/carbon-styles.spec.js-snapshots/carbon-styles-1-webkit-linux.png
  packages/form-js-carbon-styles/src/carbon-styles.js
  packages/form-js-carbon-styles/src/carbon-styles.scss
Labels: needs review, spring cleaning

#902 ci: Prevent auto-update of visual regression screenshots
  .github/workflows/UPDATE_VISUAL_SNAPSHOTS.yml
  .github/workflows/VISUAL_REGRESSION.yml
Labels: needs review, update-snapshots

#991 fix: show iframe title in editor
  packages/form-js-editor/src/render/components/editor-form-fields/EditorIFrame.js
Labels: needs review, deploy-preview

#1000 fix: repeatable entry parameters now validate with errors
  packages/form-js-editor/src/features/properties-panel/entries/NumberEntries.js
  packages/form-js-editor/src/features/properties-panel/entries/RepeatableEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/factories/simpleRangeIntegerEntryFactory.js
Labels: needs review, deploy-preview

#1013 ci: Skip carbonisation tests on master
  .github/workflows/TASKLIST_CARBONISATION.yml
Labels: needs review

#1008 chore: Update deps
  package-lock.json
  package.json
  packages/form-js-editor/package.json
  packages/form-js-playground/package.json
  packages/form-js-viewer/package.json
  packages/form-js-viewer/src/core/FormLayouter.js
Labels: needs review

#1017 fix: resize textarea on input changes
  packages/form-js-viewer/src/render/components/form-fields/Textarea.js
Labels: needs review

#1016 chore: bump properties-panel@3.18.0
  package-lock.json
  package.json
  packages/form-js-editor/package.json
  packages/form-js-editor/src/features/properties-panel/Util.js
  packages/form-js-editor/src/features/properties-panel/entries/ColumnEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/ColumnsEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/ColumnsExpressionEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/CustomValueEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/DefaultValueEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/HeightEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/HtmlEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/IFrameUrlEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/IdEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/InputKeyOptionsSourceEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/KeyEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/NumberEntries.js
  packages/form-js-editor/src/features/properties-panel/entries/PathEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/RowCountEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/StaticOptionsSourceEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/TableDataSourceEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/ValueEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/factories/simpleRangeIntegerEntryFactory.js
  packages/form-js-editor/src/features/properties-panel/groups/CustomPropertiesGroup.js
Labels: needs review
