Repository bpmn-io/form-js, pull requests merged in 2024-03, with the labels that each got.

#1086 fix: properly pass `this` variable context to dynamic list elems
  packages/form-js-viewer/src/features/repeatRender/RepeatRenderManager.js
  packages/form-js-viewer/test/spec/Form.spec.js
  packages/form-js-viewer/test/spec/dynamic-list-variables.json
Labels: needs review

#1090 chore: bump feelers and feelin, allowing overrides of special keywords from context
  package-lock.json
  packages/form-js-viewer/package.json
Labels: needs review, deploy-preview

#1091 chore: replace with `showdown` with `marked`
  package-lock.json
  packages/form-js-editor/test/spec/render/components/form-fields/helper/index.js
  packages/form-js-viewer/package.json
  packages/form-js-viewer/rollup.config.js
  packages/form-js-viewer/src/features/markdown/MarkdownRenderer.js
  packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js
Labels: needs review, deploy-preview, update-snapshots

#1089 fix: display groups with no outline with a dashed outline in the editor
  packages/form-js-editor/assets/form-js-editor-base.css
  packages/form-js-editor/src/render/components/FormEditor.js
Labels: needs review

#1088 fix: ensure dynamic list and tables interact safely
  packages/form-js-viewer/src/render/components/form-fields/Table.js
  packages/form-js-viewer/test/spec/Form.spec.js
  packages/form-js-viewer/test/spec/dynamic-list-table-filter-interaction.json
Labels: needs review

#1108 fix: improve editor focus scroll
  packages/form-js-editor/src/render/components/FormEditor.js
  packages/form-js-viewer/src/render/components/index.js
  packages/form-js-viewer/src/render/components/util/domUtil.js
  packages/form-js-viewer/src/render/hooks/useScrollIntoView.js
Labels: needs review, deploy-preview

#1110 fix: make the JSON editor readonly truly readonly
  packages/form-js-playground/src/components/JSONEditor.js
Labels: needs review

#1112 fix: prevent prototype polution through keys and paths
  packages/form-js-editor/src/features/properties-panel/Util.js
  packages/form-js-editor/src/features/properties-panel/entries/KeyEntry.js
  packages/form-js-editor/src/features/properties-panel/entries/PathEntry.js
Labels: needs review
